name: Feature Request
description: File a feature request.
title: "[Feature]: "
labels: ["feature", "triage"]
assignees:
  - devops-maturity/developers
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! 
        Please provide as much detail as possible to help us understand your request. 
        If you have a specific use case or example, please include that as well.
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Please describe the feature you would like to see added.
      placeholder: Describe the feature you want to see!
      value: "A feature was requested!"
    validations:
      required: true
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/devops-maturity/spec/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
